version: "3"
services:
  app:
    image: assignment:exness
    working_dir: /usr/code/assignment
    build:
      context: .
    volumes:
      - ./:/usr/code
    ports:
      - 5000:5000
    environment:
      - SECRET_KEY=some_key
      - ALLOWED_HOSTS=*
      - DJANGO_SETTINGS_MODULE=assignment.settings.dev
    command: python manage.py runserver 0.0.0.0:5000

  coala:
    image: fidals/coala-ci
    working_dir: /usr/code
    command: coala
    volumes:
      - ./:/usr/code

